import { Input } from "@/components/ui/input";
import { SmartContractData } from "@/lib/Interfaces/SmartContractInterface";
import { cn } from "@/lib/utils";
import React, { Dispatch, SetStateAction } from "react";

const PaymentStatement = ({
  data,
  setData,
}: {
  data: SmartContractData;
  setData: Dispatch<SetStateAction<SmartContractData>>;
}) => {
  return (
    <div className="flex items-center">
      <div className="rounded-lg bg-white px-4 py-3 leading-[50px] shadow-md">
        <span className="mr-4 text-sm">Doky is going to pay</span>

        <span
          className={cn(
            "inline-flex items-center whitespace-nowrap rounded-sm border bg-white px-2 pr-3 text-sm font-semibold text-black",
            {
              "border-red-600":
                data.percent === undefined ||
                data.percent > 100 ||
                data.percent < 0,
            },
          )}
        >
          <Input
            value={data.percent}
            onChange={(e) =>
              setData((prev) => ({
                ...prev,
                percent: parseInt(e.target.value),
              }))
            }
            placeholder="20"
            type="number"
            className={cn(
              "mx-auto inline w-8 rounded-sm border-0 bg-white px-0 text-center shadow-none !outline-none !ring-0",
              /**
               * removing arrows of input field
               */
              "[appearance:textfield] [&::-webkit-inner-spin-button]:appearance-none [&::-webkit-outer-spin-button]:appearance-none",
            )}
          />
          <span>%</span>
        </span>

        <span className="mx-4 text-sm">of the</span>

        <span
          className={cn(
            "inline-flex items-center gap-1 whitespace-nowrap rounded-sm border bg-white px-1 py-1 text-sm font-semibold text-black",
          )}
        >
          <span
            className={cn(
              "cursor-pointer rounded-sm px-8 py-1.5 text-xs text-foreground/60",
              {
                "bg-gray-300 text-foreground": data.isRevenue,
              },
            )}
            onClick={() => setData((prev) => ({ ...prev, isRevenue: true }))}
          >
            Revenue
          </span>

          <span
            className={cn(
              "cursor-pointer rounded-sm px-8 py-1.5 text-xs text-foreground/60",
              {
                "bg-gray-300 text-foreground": !data.isRevenue,
              },
            )}
            onClick={() => setData((prev) => ({ ...prev, isRevenue: false }))}
          >
            Profit
          </span>
        </span>
        <span className="mx-4 text-sm">generated by the revenue stream</span>
        {/* <Input type="text" className="flex-1 rounded-lg border p-2 md:w-44" /> */}
        <span
          className={cn(
            "inline-flex items-center whitespace-nowrap rounded-sm border bg-white px-2 pr-3 text-sm font-semibold text-black",
          )}
        >
          <Input
            value={data.stream}
            onChange={(e) =>
              setData((prev) => ({ ...prev, stream: e.target.value }))
            }
            placeholder="Doky Application"
            className={cn(
              "mx-auto inline rounded-sm border-0 bg-white px-0 text-center text-xs shadow-none !outline-none !ring-0 placeholder:text-xs",
            )}
          />
        </span>
      </div>
    </div>
  );
};
export default PaymentStatement;
