import { SmartContractData } from "@/lib/Interfaces/SmartContractInterface";
import { cn } from "@/lib/utils";
import React from "react";

const Payment = ({ data }: { data: SmartContractData }) => {
  return (
    <div className="rounded-lg bg-white px-4 py-3 leading-[50px] shadow-md">
      <span className="mr-4 text-sm">Doky is going to pay</span>

      <span
        className={cn(
          "inline-flex items-center whitespace-nowrap rounded-sm border bg-white px-4 py-1.5 text-sm font-semibold text-black",
        )}
      >
        23
        <span>%</span>
      </span>

      <span className="mx-4 text-sm">of the</span>

      <span
        className={cn(
          "inline-flex items-center gap-1 whitespace-nowrap rounded-sm border bg-white px-1 py-1 text-sm font-semibold text-black",
        )}
      >
        <span
          className={cn("rounded-sm px-8 py-1.5 text-xs text-foreground/60", {
            "bg-gray-300 text-foreground": data.isRevenue,
          })}
        >
          Revenue
        </span>

        <span
          className={cn("rounded-sm px-8 py-1.5 text-xs text-foreground/60", {
            "bg-gray-300 text-foreground": !data.isRevenue,
          })}
        >
          Profit
        </span>
      </span>
      <span className="mx-4 text-sm">generated by the revenue stream</span>
      {/* <Input type="text" className="flex-1 rounded-lg border p-2 md:w-44" /> */}
      <span
        className={cn(
          "inline-flex items-center whitespace-nowrap rounded-sm border bg-white px-4 py-1.5 text-sm font-semibold text-black",
        )}
      >
        Docky Application
      </span>
    </div>
  );
};

export default Payment;
